# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4589acc2638bbb71206082ed3ed43dd5f12953852b7ec337a580bdb051426b53e697b8694b6afbf554fbdd78ddd355a198edfda5781217f1aaddac34d4f151b

test:
  secret_key_base: ab35461a6dbfe5e02dc06117551f6b2a1b8b2ca1206f5f89a5aea930baee5478b2c56c0d7756fbddc45df18c06770c6dc05ffef3642de4b538c62b9911120da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
